//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arac_Kiralama.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0x0_2021_model_arabalar_turkiyeye_ne_zaman_gelecek_2021de_cikacak_suv_modelleri_1609741374570 {
            get {
                object obj = ResourceManager.GetObject("0x0-2021-model-arabalar-turkiyeye-ne-zaman-gelecek-2021de-cikacak-suv-modelleri-1" +
                        "609741374570", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11494050811pb9htw8ju6kbph29kcf5ahqymajkha3rppqc1nywpekzorolbdideigjvor3t1yq6sjpzlcg7ee5erhtbpwjuzfftrgwehddr79k {
            get {
                object obj = ResourceManager.GetObject("11494050811pb9htw8ju6kbph29kcf5ahqymajkha3rppqc1nywpekzorolbdideigjvor3t1yq6sjpzl" +
                        "cg7ee5erhtbpwjuzfftrgwehddr79k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453799553543 {
            get {
                object obj = ResourceManager.GetObject("1453799553543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20120623124636_68f8310b_me {
            get {
                object obj = ResourceManager.GetObject("20120623124636-68f8310b-me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20120708125408_6df43715_me {
            get {
                object obj = ResourceManager.GetObject("20120708125408-6df43715-me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _207_2071044_new_customers_new_customer_icon_png_transparent_png {
            get {
                object obj = ResourceManager.GetObject("207-2071044_new-customers-new-customer-icon-png-transparent-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3dduvarkagitlari_f54d947c {
            get {
                object obj = ResourceManager.GetObject("3dduvarkagitlari-f54d947c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _650x344_alman_araba_markalari_alman_araba_otomobil_modelleri_siralamasi_ve_listesi_1597331062493 {
            get {
                object obj = ResourceManager.GetObject("650x344-alman-araba-markalari-alman-araba-otomobil-modelleri-siralamasi-ve-listes" +
                        "i-1597331062493", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _788bea024d7b8ed7d6ad5eec7e2e59d1 {
            get {
                object obj = ResourceManager.GetObject("788bea024d7b8ed7d6ad5eec7e2e59d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _886577 {
            get {
                object obj = ResourceManager.GetObject("886577", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _892590bda5c7da8f8eaf8a80717371c4 {
            get {
                object obj = ResourceManager.GetObject("892590bda5c7da8f8eaf8a80717371c4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a36a4101fb9462c6100b70a28a19c532 {
            get {
                object obj = ResourceManager.GetObject("a36a4101fb9462c6100b70a28a19c532", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ac8fcb571095930885816134f1a9823b {
            get {
                object obj = ResourceManager.GetObject("ac8fcb571095930885816134f1a9823b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_arrows_black_wooden_background_arrows_patterns_background_with_arrows_right_arrows {
            get {
                object obj = ResourceManager.GetObject("black-arrows-black-wooden-background-arrows-patterns-background-with-arrows-right" +
                        "-arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmw_5665352__340 {
            get {
                object obj = ResourceManager.GetObject("bmw-5665352__340", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bmw_5665352__3401 {
            get {
                object obj = ResourceManager.GetObject("bmw-5665352__3401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c879475efb4a815d7a90bb936b187579 {
            get {
                object obj = ResourceManager.GetObject("c879475efb4a815d7a90bb936b187579", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap duvar_resimleri_beyaz_arka_plan_geometrik_doku {
            get {
                object obj = ResourceManager.GetObject("duvar-resimleri-beyaz-arka-plan-geometrik-doku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap duvar_resimleri_beyaz_arka_plan_geometrik_doku_jpg {
            get {
                object obj = ResourceManager.GetObject("duvar-resimleri-beyaz-arka-plan-geometrik-doku.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap E2TgCyLXsAA5pXz {
            get {
                object obj = ResourceManager.GetObject("E2TgCyLXsAA5pXz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filo_arac_kiralama {
            get {
                object obj = ResourceManager.GetObject("filo-arac-kiralama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Honda_Civic_Sedan_02_1280x720 {
            get {
                object obj = ResourceManager.GetObject("Honda_Civic_Sedan-02-1280x720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ikinci_el_araba_fiyatlari_dustu_hepsi_100_bin_lir_4936963__1_ {
            get {
                object obj = ResourceManager.GetObject("ikinci-el-araba-fiyatlari-dustu-hepsi-100-bin-lir-4936963 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap old_black_wall_background_texture_600w_504932662 {
            get {
                object obj = ResourceManager.GetObject("old-black-wall-background-texture-600w-504932662", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_shihabsha_zin_407615 {
            get {
                object obj = ResourceManager.GetObject("pexels-shihabsha-zin-407615", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scion_scion_fr_s_scion_iq_scion_tc_scion_xd_scion_xb_car_vehicle_simple_background_dual_monitors_multiple_display_reflection_wallpaper_preview {
            get {
                object obj = ResourceManager.GetObject("scion-scion-fr-s-scion-iq-scion-tc-scion-xd-scion-xb-car-vehicle-simple-backgroun" +
                        "d-dual-monitors-multiple-display-reflection-wallpaper-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
